# Generated by Django 6.0.4 on 2026-04-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
